package com.devsuperior.dsvendas.repositories;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.devsuperior.dsvendas.dto.LogDashBoardProcessamentosDTO;

import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.List;

@Repository
public class LogDashBoardProcessamentosRepository {
    private final JdbcTemplate jdbcTemplate;

    @Autowired
    public LogDashBoardProcessamentosRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }
    @Transactional(readOnly = true)
    public List<LogDashBoardProcessamentosDTO> buscarLogDashBoardProcessamentoss() {
    	 String sql =  " select 'monitoracao v.1' as monitoracao,                            "
    			 +" es.id_estrutura ,                                                        "
    			 +" es.sigla,                                                                " 
    			 +" case                                                                     " 
    			 +" when ltrim(es.id_estrutura) in (8590,                                    "
    			 +" 106539,                                                                  "
    			 +" 106540,                                                                  "
    			 +" 6788,                                                                    "
    			 +" 8648,                                                                    "
    			 +" 106528,                                                                  "
    			 +" 108885,                                                                  "
    			 +" 106533,                                                                  "
    			 +" 106538,                                                                  "
    			 +" 107468,                                                                  "
    			 +" 108872,                                                                  "
    			 +" 108873,                                                                  "
    			 +" 108874,                                                                  "
    			 +" 108875,                                                                  "
    			 +" 108877,                                                                  "
    			 +" 108879,                                                                  "
    			 +" 108871,                                                                  "
    			 +" 7488,                                                                    "
    			 +" 7508) and es.cargatotal = 'n' then                                       "
    			 +" 'full'                                                                   "
    			 +" else                                                                     "
    			 +" UPPER(decode(es.cargatotal, 'n', 'mvto', 'full'))                               "
    			 +" end tipo_carga,                                                          " 
    			 +" ca.data as data_calendario,                                              " 
    			 +" case                                                                     " 
    			 +" when trim(lo.hora) is null then                                          "
    			 +" ('00:00:00 ')                                                            "
    			 +" else                                                                     "
    			 +" to_char(lo.hora, 'hh24:mi:ss')                                           "
    			 +" end hora,                                                                " 
    			 +" nvl(trim(lo.id_seqlog), 0) id_seqlog,                                    " 
    			 +"   to_char(case                                                                                       "           
                 +" when trim(LO.totalregistros) is null  and TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) < TRUNC(SYSDATE)   "                       
    	         +"  	                        THEN  ('SEM MVTO')                                                       "
    	         +" when trim(LO.totalregistros) is null  and TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) >= TRUNC(SYSDATE)  "                       
    	         +"                 THEN  ('PENDENTE')                "
    	         +" else 'PROCESSADO'                                  "                            
    	         +" end ) STATUS_LOG , "
    	         +" case                                                                     " 
    			 +" when trim(lo.totalregistros) is null then                                "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.totalregistros)                                                  "
    			 +" end totalregistros,                                                      " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regcorretos) is null then                                   "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regcorretos)                                                     "
    			 +" end regcorretos,                                                         " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regincorretos) is null then                                 "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regincorretos)                                                   "
    			 +" end regincorretos,                                                       " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regenvvencido) is null then                                 "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regenvvencido)                                                   "
    			 +" end regenvvencido,                                                       " 
    			 +" case                                                                     " 
    			 +" when trim(lo.totalregistros) = 0 or trim(lo.totalregistros) is null then "
    			 +" to_char(0, '999g999g999g999g990d00') || '%'                              "
    			 +" else                                                                     "
    			 +" concat(to_char(((to_number(lo.regcorretos) * 100) /                      "
    			 +" to_number(lo.totalregistros)),                                           "
    			 +" '999g999g999g999g990d00'),                                               "
    			 +" '%')                                                                     "
    			 +" end percentual_correto,                                                  " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regincorretos) = 0 or trim(lo.regincorretos) is null then   "
    			 +" to_char(0, '999g999g999g999g990d00') || '%'                              "
    			 +" else                                                                     "
    			 +" concat(to_char(((to_number(lo.regincorretos) * 100) /                    "
    			 +" to_number(lo.totalregistros)),                                           "
    			 +" '999g999g999g999g990d00'),                                               "
    			 +" '%')                                                                     "
    			 +" end percentual_incorreto,                                                " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regenvvencido) = 0 or trim(lo.regenvvencido) is null then   "
    			 +" to_char(0, '999g999g999g999g990d00') || '%'                              "
    			 +" else                                                                     "
    			 +" concat(to_char(((to_number(lo.regenvvencido) * 100) /                    "
    			 +" to_number(lo.totalregistros)),                                           "
    			 +" '999g999g999g999g990d00'),                                               "
    			 +" '%')                                                                     "
    			 +" end percentual_vencidos,                                                 " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regenvinclusao) is null then                                "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regenvinclusao)                                                  "
    			 +" end regenvinclusao,                                                      " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regenvalteracao) is null then                               "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regenvalteracao)                                                 "
    			 +" end regenvalteracao,                                                     " 
    			 +" case                                                                     " 
    			 +" when trim(lo.regenvcancelamento) is null then                            "
    			 +" lpad('0', '1')                                                           "
    			 +" else                                                                     "
    			 +" trim(lo.regenvcancelamento)                                              "
    			 +" end regenvcancelamento,                                                  " 
    			 +" es.descricao nm_estrutura,                                               " 
    			 +" es.id_clientecorporativo as id_cliente,                                  " 
    			 +" case                                                                     " 
    			 +" when trim(ct.razaosocialclicorp) is null then                            "
    			 +" es.descricao                                                             "
    			 +" else                                                                     "
    			 +" ct.razaosocialclicorp                                                    "
    			 +" end nm_cliente,                                                          " 
    			 +" es.id_contrato,                                                          " 
    			 +" ct.titulo nm_contrato,                                                   " 
    			 +" (case es.id_tipocarteira                                                 " 
    			 +" when 1 then                                                              "
    			 +" 'veículo'                                                                "
    			 +" when 2 then                                                              "
    			 +" 'residencia'                                                             "
    			 +" when 3 then                                                              "
    			 +" 'pessoa'                                                                 "
    			 +" when 4 then                                                              "
    			 +" 'funeral'                                                                "
    			 +" else                                                                     "
    			 +" 'sei la'                                                                 "
    			 +" end) segmento,                                                           " 
    			 +" es.local_arquivo,                                                        " 
    			 +" to_char(ca.data, 'yyyy/mm') ano_mes,                                     " 
    			 +" rownum indece                                                            "
    			 +" from processamento.calendario_producao ca                                "      
    			 +" full outer join sgr.estrutura es                                         "      
    			 +" on (es.id_estrutura is not null and es.id_estrutura is not null and      "    
    			 +" es.descricao not like '%CANCEL%' and                                     " 
    			 +" es.descricao not like '%CANCEL%')                                        " 
    			 +" left join sgr.logentrada lo                                              "      
    			 +" on (ca.data = lo.data and                                                "    
    			 +" (lo.arquivoorigem like '%' || es.sigla || '%'))                          " 
    			 +" left join sgr.contrato ct                                                "      
    			 +" on (es.id_clientecorporativo = ct.id_clientecorporativo and              "    
    			 +" es.id_contrato = ct.id_contrato) and ct.titulo not like '%CANCEL%'       " 
    			 +" where 0 = 0                                                              "
    			 +" and ca.data is not null                                                  "      
    			 +" and (lo.totalregistros) <> 0                                             "
    			 +" and ca.DATA > trunc(sysdate -180) "
    			 +" order by es.id_estrutura, ca.data desc , lo.id_seqlog asc                                  ";
        return jdbcTemplate.query(sql, new BeanPropertyRowMapper<>(LogDashBoardProcessamentosDTO.class));
    }
    
    
    
    @Transactional(readOnly = true)
   public List<LogDashBoardProcessamentosDTO> buscarLogDashBoardProcessamentosData(Date dataInicio, Date dataFim) {
	   String sql = "select 'MONITORACAO-DIARIA-PAG*' AS MONITORACAO,                                      "
       		+"       ES.ID_ESTRUTURA,                                                          "
       		+"       ES.SIGLA,                                                                 "
       		+"       case                                                                      "
       		+"         when LTRIM(ES.ID_ESTRUTURA) IN (8590,                                   "
       		+"                                         106539,                                 "
       		+"                                         106540,                                 "
       		+"                                         6788,                                   "
       		+"                                         8648,                                   "
       		+"                                         106528,                                 "
       		+"                                         108885,                                 "
       		+"                                         106533,                                 "
       		+"                                         106538,                                 "
       		+"                                         107468,                                 "
       		+"                                         108872,                                 "
       		+"                                         108873,                                 "
       		+"                                         108874,                                 "
       		+"                                         108875,                                 "
       		+"                                         108877,                                 "
       		+"                                         108879,                                 "
       		+"                                         108871,                                 "
       		+"                                         7488,                                   "
       		+"                                         7508) and ES.cargatotal = 'N' THEN      "
       		+"          'FULL'                                                                 "
       		+"         else                                                                    "
       		+"          decode(ES.cargatotal, 'N', 'MVTO', 'FULL')                             "
       		+"       end TIPO_CARGA,                                                           "
       		+"       CA.DATA as DATA_CALENDARIO,                                               "
       		+"       CASE                                                                      "
       		+"         WHEN TRIM(LO.HORA) IS NULL THEN                                         "
       		+"          ('00:00:00 ')                                                          "
       		+"         ELSE                                                                    "
       		+"          TO_CHAR(LO.HORA, 'HH24:MI:SS')                                         "
       		+"       END HORA,                                                                 "
       		+"       NVL(TRIM(LO.ID_SEQLOG), 0) ID_SEQLOG,                                     "
       		+"       CASE                                                                      "
       		+"         WHEN TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) <= TRUNC(SYSDATE) THEN     "
       		+"          ('SEM_MOVTOS')                                                         "
       		+"         WHEN TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) > TRUNC(SYSDATE) THEN      "
       		+"          ('PENDENTES ')                                                         "
       		+"         ELSE                                                                    "
       		+"          ('PROCESSADO')                                                         "
       		+"       END STATUS_LOG,                                                           "
       		+"       case                                                                      "
       		+"         when trim(LO.totalregistros) is null then                               "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.totalregistros)                                                "
       		+"       end totalregistros,                                                       "
       		+"       case                                                                      "
       		+"         when trim(LO.regcorretos) is null then                                  "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regcorretos)                                                   "
       		+"       end regcorretos,                                                          "
       		+"       case                                                                      "
       		+"         when trim(LO.regincorretos) is null then                                "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regincorretos)                                                 "
       		+"       end regincorretos,                                                        "
       		+"       case                                                                      "
       		+"         when trim(LO.regenvvencido) is null then                                "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regenvvencido)                                                 "
       		+"       end regenvvencido,                                                        "
       		+"       case                                                                      "
       		+"         when TRIM(LO.totalregistros) = 0 OR TRIM(LO.totalregistros) is null then"
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(lO.regcorretos) * 100) /                    "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_CORRETO,                                                   "
       		+"       case                                                                      "
       		+"         when TRIM(LO.regincorretos) = 0 or TRIM(LO.regincorretos) is null then  "
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(LO.regincorretos) * 100) /                  "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_INCORRETO,                                                 "
       		+"       case                                                                      "
       		+"         when TRIM(LO.regenvvencido) = 0 or TRIM(LO.regenvvencido) is null then  "
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(LO.regenvvencido) * 100) /                  "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_VENCIDOS,                                                  "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVINCLUSAO) is null then                               "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVINCLUSAO)                                                "
       		+"       end REGENVINCLUSAO,                                                       "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVALTERACAO) is null then                              "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVALTERACAO)                                               "
       		+"       end REGENVALTERACAO,                                                      "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVCANCELAMENTO) is null then                           "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVCANCELAMENTO)                                            "
       		+"       end REGENVCANCELAMENTO,                                                   "
       		+"       ES.DESCRICAO NM_ESTRUTURA,                                                "
       		+"       ES.ID_CLIENTECORPORATIVO AS ID_CLIENTE,                                   "
       		+"       case                                                                      "
       		+"         when trim(ct.razaosocialclicorp) is null then                           "
       		+"          ES.DESCRICAO                                                           "
       		+"         else                                                                    "
       		+"          ct.razaosocialclicorp                                                  "
       		+"       end NM_CLIENTE,                                                           "
       		+"       ES.ID_CONTRATO,                                                           "
       		+"       ct.titulo NM_contrato,                                                    "
       		+"       (CASE ES.id_tipocarteira                                                  "
       		+"         WHEN 1 THEN                                                             "
       		+"          'VEÍCULO'                                                              "
       		+"         WHEN 2 THEN                                                             "
       		+"          'RESIDENCIA'                                                           "
       		+"         WHEN 3 THEN                                                             "
       		+"          'PESSOA'                                                               "
       		+"         WHEN 4 THEN                                                             "
       		+"          'FUNERAL'                                                              "
       		+"         ELSE                                                                    "
       		+"          'SEI LA'                                                               "
       		+"       END) SEGMENTO,                                                            "
       		+"       ES.LOCAL_ARQUIVO,                                                         "
       		+"       TO_CHAR(CA.DATA, 'YYYY/MM') ANO_MES                                       "
       		+"  from PROCESSAMENTO.CALENDARIO_PRODUCAO CA                                      "
       		+"  full outer join sgr.estrutura ES                                               "
       		+"    ON (ES.ID_ESTRUTURA IS NOT NULL AND ES.ID_ESTRUTURA IS NOT NULL AND          "
       		+"       ES.DESCRICAO NOT LIKE '%CANCEL%' AND                                      "
       		+"       ES.DESCRICAO NOT LIKE '%CANCEL%')                                         "
       		+"  left join sgr.logentrada LO                                                    "
       		+"    ON (CA.DATA = LO.DATA AND                                                    "
       		+"       (LO.arquivoorigem like '%' || ES.SIGLA || '%'))                           "
       		+"  left join sgr.contrato CT                                                      "
       		+"    ON (ES.id_clientecorporativo = ct.id_clientecorporativo and                  "
       		+"       ES.id_contrato = ct.id_contrato and ct.titulo not like '%CANCEL%')        "
       		+" WHERE 0 = 0    "
       		+"   AND ES.ID_ESTRUTURA IN (10978, 10827)                                         "
       		+ "  AND CA.DATA IS NOT NULL                                                       "
				+ "  and  l.DATA >= ? AND l.DATA <= ?                                              "
       		+" ORDER BY ES.ID_ESTRUTURA, CA.DATA DESC , lo.id_seqlog asc";
  
        
        // return jdbcTemplate.query(sql, new Object[]{dataInicio, dataFim}, new BeanPropertyRowMapper<>(LogDashBoardProcessamentosDTO.class));
        List<LogDashBoardProcessamentosDTO> logs = jdbcTemplate.query(sql, new Object[]{dataInicio, dataFim}, new BeanPropertyRowMapper<>(LogDashBoardProcessamentosDTO.class));
        if (logs.isEmpty()) {
            // Não há movimento para o intervalo de datas
            LogDashBoardProcessamentosDTO semMovimento = new LogDashBoardProcessamentosDTO();
            semMovimento.setNM_ESTRUTURA("Sem movimento");
            return Collections.singletonList(semMovimento);
        }

        return logs;
   }

    @Transactional(readOnly = true)
   public List<LogDashBoardProcessamentosDTO> buscarLogDashBoardProcessamentosIdEstrutura(String id_estrutura) {
	   String sql = "select 'MONITORACAO-DIARIA' AS MONITORACAO,                                      "
       		+"       ES.ID_ESTRUTURA,                                                          "
       		+"       ES.SIGLA,                                                                 "
       		+"       case                                                                      "
       		+"         when LTRIM(ES.ID_ESTRUTURA) IN (8590,                                   "
       		+"                                         106539,                                 "
       		+"                                         106540,                                 "
       		+"                                         6788,                                   "
       		+"                                         8648,                                   "
       		+"                                         106528,                                 "
       		+"                                         108885,                                 "
       		+"                                         106533,                                 "
       		+"                                         106538,                                 "
       		+"                                         107468,                                 "
       		+"                                         108872,                                 "
       		+"                                         108873,                                 "
       		+"                                         108874,                                 "
       		+"                                         108875,                                 "
       		+"                                         108877,                                 "
       		+"                                         108879,                                 "
       		+"                                         108871,                                 "
       		+"                                         7488,                                   "
       		+"                                         7508) and ES.cargatotal = 'N' THEN      "
       		+"          'FULL'                                                                 "
       		+"         else                                                                    "
       		+"          decode(ES.cargatotal, 'N', 'MVTO', 'FULL')                             "
       		+"       end TIPO_CARGA,                                                           "
       		+"       CA.DATA as DATA_CALENDARIO,                                               "
       		+"       CASE                                                                      "
       		+"         WHEN TRIM(LO.HORA) IS NULL THEN                                         "
       		+"          ('00:00:00 ')                                                          "
       		+"         ELSE                                                                    "
       		+"          TO_CHAR(LO.HORA, 'HH24:MI:SS')                                         "
       		+"       END HORA,                                                                 "
       		+"       NVL(TRIM(LO.ID_SEQLOG), 0) ID_SEQLOG,                                     "
       		+"       CASE                                                                      "
       		+"         WHEN TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) <= TRUNC(SYSDATE) THEN     "
       		+"          ('SEM_MOVTOS')                                                         "
       		+"         WHEN TRIM(LO.DATA) IS NULL AND TRIM(CA.DATA) > TRUNC(SYSDATE) THEN      "
       		+"          ('PENDENTES ')                                                         "
       		+"         ELSE                                                                    "
       		+"          ('PROCESSADO')                                                         "
       		+"       END STATUS_LOG,                                                           "
       		+"       case                                                                      "
       		+"         when trim(LO.totalregistros) is null then                               "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.totalregistros)                                                "
       		+"       end totalregistros,                                                       "
       		+"       case                                                                      "
       		+"         when trim(LO.regcorretos) is null then                                  "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regcorretos)                                                   "
       		+"       end regcorretos,                                                          "
       		+"       case                                                                      "
       		+"         when trim(LO.regincorretos) is null then                                "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regincorretos)                                                 "
       		+"       end regincorretos,                                                        "
       		+"       case                                                                      "
       		+"         when trim(LO.regenvvencido) is null then                                "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.regenvvencido)                                                 "
       		+"       end regenvvencido,                                                        "
       		+"       case                                                                      "
       		+"         when TRIM(LO.totalregistros) = 0 OR TRIM(LO.totalregistros) is null then"
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(lO.regcorretos) * 100) /                    "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_CORRETO,                                                   "
       		+"       case                                                                      "
       		+"         when TRIM(LO.regincorretos) = 0 or TRIM(LO.regincorretos) is null then  "
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(LO.regincorretos) * 100) /                  "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_INCORRETO,                                                 "
       		+"       case                                                                      "
       		+"         when TRIM(LO.regenvvencido) = 0 or TRIM(LO.regenvvencido) is null then  "
       		+"          to_char(0, '999G999G999G999G990D00') || '%'                            "
       		+"         else                                                                    "
       		+"          concat(to_char(((TO_NUMBER(LO.regenvvencido) * 100) /                  "
       		+"                         to_number(LO.totalregistros)),                          "
       		+"                         '999G999G999G999G990D00'),                              "
       		+"                 '%')                                                            "
       		+"       end PERCENTUAL_VENCIDOS,                                                  "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVINCLUSAO) is null then                               "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVINCLUSAO)                                                "
       		+"       end REGENVINCLUSAO,                                                       "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVALTERACAO) is null then                              "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVALTERACAO)                                               "
       		+"       end REGENVALTERACAO,                                                      "
       		+"       case                                                                      "
       		+"         when trim(LO.REGENVCANCELAMENTO) is null then                           "
       		+"          lpad('0', '1')                                                         "
       		+"         else                                                                    "
       		+"          trim(LO.REGENVCANCELAMENTO)                                            "
       		+"       end REGENVCANCELAMENTO,                                                   "
       		+"       ES.DESCRICAO NM_ESTRUTURA,                                                "
       		+"       ES.ID_CLIENTECORPORATIVO AS ID_CLIENTE,                                   "
       		+"       case                                                                      "
       		+"         when trim(ct.razaosocialclicorp) is null then                           "
       		+"          ES.DESCRICAO                                                           "
       		+"         else                                                                    "
       		+"          ct.razaosocialclicorp                                                  "
       		+"       end NM_CLIENTE,                                                           "
       		+"       ES.ID_CONTRATO,                                                           "
       		+"       ct.titulo NM_contrato,                                                    "
       		+"       (CASE ES.id_tipocarteira                                                  "
       		+"         WHEN 1 THEN                                                             "
       		+"          'VEÍCULO'                                                              "
       		+"         WHEN 2 THEN                                                             "
       		+"          'RESIDENCIA'                                                           "
       		+"         WHEN 3 THEN                                                             "
       		+"          'PESSOA'                                                               "
       		+"         WHEN 4 THEN                                                             "
       		+"          'FUNERAL'                                                              "
       		+"         ELSE                                                                    "
       		+"          'SEI LA'                                                               "
       		+"       END) SEGMENTO,                                                            "
       		+"       ES.LOCAL_ARQUIVO,                                                         "
       		+"       TO_CHAR(CA.DATA, 'YYYY/MM') ANO_MES                                       "
       		+"  from PROCESSAMENTO.CALENDARIO_PRODUCAO CA                                      "
       		+"  full outer join sgr.estrutura ES                                               "
       		+"    ON (ES.ID_ESTRUTURA IS NOT NULL AND ES.ID_ESTRUTURA IS NOT NULL AND          "
       		+"       ES.DESCRICAO NOT LIKE '%CANCEL%' AND                                      "
       		+"       ES.DESCRICAO NOT LIKE '%CANCEL%')                                         "
       		+"  left join sgr.logentrada LO                                                    "
       		+"    ON (CA.DATA = LO.DATA AND                                                    "
       		+"       (LO.arquivoorigem like '%' || ES.SIGLA || '%'))                           "
       		+"  left join sgr.contrato CT                                                      "
       		+"    ON (ES.id_clientecorporativo = ct.id_clientecorporativo and                  "
       		+"       ES.id_contrato = ct.id_contrato and ct.titulo not like '%CANCEL%')        "
       		+" WHERE 0 = 0    "
       		+"   AND ES.ID_ESTRUTURA IN (10978, 10827)                                         "
       		+ "  AND CA.DATA IS NOT NULL                                                       "
				+ "  and  l.DATA >= ? AND l.DATA <= ?                                              "
       		+" ORDER BY ES.ID_ESTRUTURA, CA.DATA DESC , lo.id_seqlog asc";
       
       // return jdbcTemplate.query(sql, new Object[]{dataInicio, dataFim}, new BeanPropertyRowMapper<>(LogDashBoardProcessamentosDTO.class));
       List<LogDashBoardProcessamentosDTO> logs = jdbcTemplate.query(sql, new Object[]{id_estrutura}, new BeanPropertyRowMapper<>(LogDashBoardProcessamentosDTO.class));
       if (logs.isEmpty()) {
           // Não há movimento para o intervalo de datas
           LogDashBoardProcessamentosDTO semMovimento = new LogDashBoardProcessamentosDTO();
           semMovimento.setNM_ESTRUTURA("Sem movimento");
           return Collections.singletonList(semMovimento);
       }

       return logs;
  }
    
   
   
    
}